apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-storage-exporter-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-storage-exporter-clusterrole
subjects:
  - kind: ServiceAccount
    name: local-storage-exporter-serviceaccount
    namespace: default